name: BuildAndTest
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -c Release --output ./Release
      - name: lista plikow
        run: ls Release
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: FTP Deploy to WP Engine (Staging)
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: swsw.somee.com
          username: '${{ secrets.USER}}'
          password: '${{ secrets.PASSWORD }}'
          local-dir: ./Release/
          server-dir: www.swsw.somee.com/
