name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.3
    - name: Install dependencies
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish AngielskiNauka.sln --configuration Release --framework netcoreapp8.0 --output ./publish --runtime win-x86  --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true
