# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release --output ./Release
  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: swsw.somee.com
        username: ${{ secrets.USER}}
        password: ${{ secrets.PASSWORD }}
        local-dir: ./Release/
        server-dir: www.swsw.somee.com/
