name: BuildAndTest
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Display the path
        run: echo %PATH%
        shell: cmd
      - name: unix
        run: pwd

        
