# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the solution
      run: dotnet build --no-restore --configuration Release

    - name: Publish the build artifacts
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload the artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-app
        path: ./publish
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: swsw.somee.com
        username: ${{ secrets.USER}}
        password: ${{ secrets.PASSWORD }}
        local-dir: ./publish/
        server-dir: www.swsw.somee.com/
