name: BuildAndTest
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: lista plikow
        run: ls
      - name: unix
        run: pwd

        
