name: Build and Deploy ASP.NET Core

on:
  push:
    branches:
      - main # lub inna gałąź, której używasz
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Pobierz kod źródłowy
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Zainstaluj .NET Core
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0 # Dostosuj wersję .NET do swojego projektu

    # 3. Przygotuj projekt
    - name: Restore dependencies
      run: dotnet restore

    # 4. Zbuduj projekt
    - name: Build project
      run: dotnet build --configuration Release

    # 5. Opublikuj projekt
    - name: Publish project
      run: dotnet publish -c Release -o ./publish

    # 6. Wdrożenie (np. na Azure lub inny serwer)
    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.2
      with:
        host: swsw.somee.com
        username: swdowia1
        password: ZAQ!2wsxcde3
        source: ./publish/
        target: /www.swsw.somee.com/
